services:
  traefik:
    volumes:
      - ./traefik/acme:/acme
    command:
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=memrok-prod
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=${DNS_PROVIDER}
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --api.dashboard=false
      - --api.insecure=false
      - --log.level=WARN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${MEMROK_PROXY_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"

  authelia:
    volumes:
      - ./authelia/configuration.prod.yml:/config/configuration.yml:ro
      - ./authelia/users_database.yml:/config/users_database.yml:ro
      - authelia-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`${MEMROK_AUTH_DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${MEMROK_AUTH_DOMAIN}"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

  memrok:
    image: memrok/app:${MEMROK_VERSION:-latest}
    container_name: memrok-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memrok.rule=Host(`${MEMROK_APP_DOMAIN}`)"
      - "traefik.http.routers.memrok.entrypoints=websecure"
      - "traefik.http.routers.memrok.tls.certresolver=letsencrypt"
      - "traefik.http.routers.memrok.middlewares=authelia@docker"
    networks:
      - memrok

networks:
  memrok:
    name: ${DOCKER_NETWORK:-memrok-prod}