services:
  traefik:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    command:
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=memrok-dev
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    labels:
      - "traefik.http.routers.traefik.rule=Host(`${MEMROK_PROXY_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

  zitadel:
    volumes:
      - ./zitadel/machinekey:/machinekey
      - ./zitadel/pat:/pat
    environment:
      ZITADEL_TLS_ENABLED: false
    labels:
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"

  postgres:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  qdrant:
    ports:
      - "${QDRANT_HOST_PORT:-6334}:6334"
      - "${QDRANT_WEB_UI_PORT:-6333}:6333"
    environment:
      # Development mode - web UI enabled
      QDRANT__WEB_UI__ENABLED: true
      QDRANT__SERVICE__ENABLE_TLS: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`${MEMROK_VECTORS_DOMAIN}`)"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.tls=true"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"

networks:
  memrok:
    name: ${DOCKER_NETWORK:-memrok-dev}
