---
###############################################################
#                   Authelia Configuration                   #
###############################################################

jwt_secret: ${JWT_SECRET}
default_redirection_url: https://${MEMROK_APP_DOMAIN}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "${MEMROK_APP_DOMAIN}"
      policy: two_factor
    - domain: "${MEMROK_PROXY_DOMAIN}"
      policy: two_factor

session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  expiration: 3600
  inactivity: 300
  domain: dev.memrok.com

storage:
  encryption_key: ${STORAGE_ENCRYPTION_KEY}
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt