---
###############################################################
#                Authelia Development Configuration          #
###############################################################

jwt_secret: ${JWT_SECRET}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "app.dev.memrok.com"
      policy: one_factor  # Easier for development
    - domain: "proxy.dev.memrok.com"
      policy: one_factor  # Easier for development

session:
  secret: ${SESSION_SECRET}
  cookies:
    - name: 'authelia_session'
      domain: 'dev.memrok.com'
      authelia_url: 'https://auth.dev.memrok.com'
      expiration: '1 hour'
      inactivity: '5 minutes'
      default_redirection_url: 'https://app.dev.memrok.com'

storage:
  encryption_key: ${STORAGE_ENCRYPTION_KEY}
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt