services:
  traefik:
    image: traefik:v3.0
    command:
      # API and Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true" # For development only
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${DOCKER_NETWORK}"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/data
    networks:
      - default
    labels:
      - "traefik.enable=true"
      # Traefik dashboard routing
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${MEMROK_PROXY_DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard.service=traefik-dashboard"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
    restart: unless-stopped

volumes:
  traefik-data:


networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
