# Traefik configuration
api:
  dashboard: true
  insecure: true  # Only for development - disable in production

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: ${NETWORK_NAME}

# Basic configuration - extend for production with certificates
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

# Redirect HTTP to HTTPS (uncomment for production)
# entryPoints:
#   web:
#     redirections:
#       entryPoint:
#         to: websecure
#         scheme: https