http:
  routers:
    # All routes - authentication will be handled by Nuxt OIDC Auth module
    memrok-app:
      rule: "Host(`app.dev.memrok.com`)"
      entryPoints:
        - websecure
      service: memrok-app
      tls: true

  services:
    memrok-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"  # Nuxt dev server