# Authelia Configuration
server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

jwt_secret: ${AUTHELIA_JWT_SECRET}

default_redirection_url: https://${DOMAIN}

totp:
  issuer: memrok

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: ${DOMAIN}
      policy: one_factor

session:
  name: authelia_session
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 3600
  inactivity: 300
  domain: ${DOMAIN}

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /data/db.sqlite3
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

notifier:
  filesystem:
    filename: /data/notification.txt